app:
  kafka:
    bootstrap_servers: 
      - flying-ghoul-13808-us1-kafka.upstash.io:9092
    client_id: 'newyeti-telemetry-producer'
    sasl_mechanism: SCRAM-SHA-256
    security_protocol: SASL_SSL
    sasl_plain_username: Zmx5aW5nLWdob3VsLTEzODA4JK8Ko_8y0QKzRZOlFK6CSN1hNX6uJeoFsgqms64
    sasl_plain_password: 3d9f1534b0e847afa95090cc9d7d7d7e
    