
---
kafka_api:
  uri: "https://api.upstash.com/v2/kafka"
  clusters:
  - api_key: ${NEWYETI_PROD_CLUSTER0_KEY}
    email: ${NEWYETI_PROD_CLUSTER0_EMAIL}
    cluster: 
      name: newyeti-prod-cluster-0
      region: us-east-1
      multizone: true
    topics:
    - teams
    - fixtures
    connnectors:
      mongo:
      - teams

  - api_key: ${NEWYETI_PROD_CLUSTER1_KEY}
    email: ${NEWYETI_PROD_CLUSTER1_EMAIL}
    cluster: 
      name: newyeti-prod-cluster-1
      region: us-east-1
      multizone: true
    topics:
    - teams
    - fixtures
    connnectors:
      mongo:
      - teams

  - api_key: ${NEWYETI_PROD_CLUSTER2_KEY}
    email: ${NEWYETI_PROD_CLUSTER2_EMAIL}
    cluster: 
      name: newyeti-prod-cluster-2
      region: us-east-1
      multizone: true
    topics:
    - teams
    - fixtures
    connectors:
    - newyeti.mongo.football.teams.sink

  - api_key: ${NEWYETI_PROD_CLUSTER3_KEY}
    email: ${NEWYETI_PROD_CLUSTER3_EMAIL}
    cluster: 
      name: newyeti-prod-cluster-3
      region: us-east-1
      multizone: true
    topics:
    - teams
    - fixtures
    connectors:
    - newyeti.mongo.football.teams.sink

  topic_configs:
    teams:
      name: newyeti.source.teams.v1
      partitions: 2
      retention_time: 604800000
      retention_size: 268435456
      max_message_size: 1048576
      cleanup_policy: delete

    fixtures:
      name: newyeti.source.fixtures.v1
      partitions: 2
      retention_time: 604800000
      retention_size: 268435456
      max_message_size: 1048576
      cleanup_policy: delete

  connector_configs:
    mongo:
      teams:
        name: newyeti.mongo.football.teams.sink
        properties:
          collection: teams
          connection.uri: mongodb+srv://{MONGO_USERNAME}:{MONGO_PASSWORD@{MONGO_HOSTNAME}
          connector.class: com.mongodb.kafka.connect.MongoSinkConnector
          database: football
          topics: newyeti.source.teams.v1
      fixtures:
        name: newyeti.mongo.football.fixtures.sink
        properties:
          collection: fixtures
          connection.uri: mongodb+srv://{MONGO_USERNAME}:{MONGO_PASSWORD@{MONGO_HOSTNAME}
          connector.class: com.mongodb.kafka.connect.MongoSinkConnector
          database: football
          topics: newyeti.source.fixtures.v1
