defaults:
  - stack
  - service
  - _self_

app:
  name: Telemetry CLI
  stacks:
    - ${newyeti-1}
    - ${newyeti-2}
    - ${newyeti-3}
  control:
    redis:
      client_id: ${oc.env:NEWYETI_CONTROL_CLIENT_ID}-redis
      host: ${oc.env:NEWYETI_CONTROL_REDIS_HOST}
      port: ${oc.env:NEWYETI_CONTROL_REDIS_PORT}
      password: ${oc.env:NEWYETI_CONTROL_REDIS_PASSWORD}
  service: ${service}
  message:
    batch_size: 50
    kafka_daily_limit: 10000
    kafka_per_second_limit: 100
    redis_daily_limit: 10000
    key_expiry_in_days: 7
