defaults:
  - stack
  - service
  - _self_
  
app:
  name: Telemetry CLI
  stacks: 
  - ${newyeti-1}
  - ${newyeti-2}
  - ${newyeti-3}
  control:
    redis:
      client_id: ${oc.env:NEWYETI_CLIENT_ID}-redis
      host: ${oc.env:NEWYETI-CONTROL_REDIS_HOST}
      port: ${oc.env:NEWYETI-CONTROL_REDIS_PORT}
      password: ${oc.env:NEWYETI-CONTROL_REDIS_PASSWORD}
  service: ${service}
