kafka:
  bootstrap_servers: 
    - flying-ghoul-13808-us1-kafka.upstash.io:9092
  client_id: 'newyeti-telemetry-producer'
  sasl_mechanism: SCRAM-SHA-256
  security_protocol: SASL_SSL
  sasl_plain_username: ${oc.env:KAFKA_USERNAME}
  sasl_plain_password: ${oc.env:KAFKA_PASSWORD}
