kafka:
  bootstrap_servers: 
    - unbiased-coral-13008-us1-kafka.upstash.io:9092
  client_id: 'newyeti-cluster-0'
  sasl_mechanism: SCRAM-SHA-256
  security_protocol: SASL_SSL
  sasl_plain_username: ${oc.env:KAFKA_USERNAME}
  sasl_plain_password: ${oc.env:KAFKA_PASSWORD}
