service:
  teams:
    filename: teams.csv
    topic: newyeti.telemetry.teams.v1
  standings:
    filename: standings.csv
    topic: newyeti.telemetry.standings.v1
  fixtures:
    filename: fixtures.csv
    topic: newyeti.telemetry.fixtures.v1
  fixture_events:
    filename: fixture-events.csv
    topic: newyeti.telemetry.fixture-events.v1
  fixture_lineups:
    filename: fixture-lineups.csv
    topic: newyeti.telemetry.fixture-lineups.v1
  fixture_player_stats:
    filename: fixture-player-stats.csv
    topic: newyeti.telemetry.fixture-player-stats.v1
  top_scorers:
    filename: top-scorers.csv
    topic: newyeti.telemetry.top_scorers.v1
