service:
  teams:
    filename: teams.csv
    topic: newyeti.source.teams.v1
  standings:
    filename: standings.csv
    topic: newyeti.source.standings.v1
  fixtures:
    filename: fixtures.csv
    topic: newyeti.source.fixtures.v1
  fixture_events:
    filename: fixture-events.csv
    topic: newyeti.source.fixture_events.v1
  fixture_lineups:
    filename: fixture-lineups.csv
    topic: newyeti.source.fixture_lineups.v1
  fixture_player_stats:
    filename: fixture-player-stats.csv
    topic: newyeti.source.fixture_player_stats.v1
  top_scorers:
    filename: top-scorers.csv
    topic: newyeti.source.top_scorers.v1
